services:
  frontend-app:
    image: andreypolezhaiev/avtodiva-frontend:latest
    container_name: avtodiva-frontend
    build: .
    ports:
      - "${FRONTEND_PORT}:${DOCKER_PORT}"
    environment:
      - NGINX_PORT=${NGINX_PORT}
      - BACKEND_HOST=${BACKEND_HOST}
      - BACKEND_PORT=${BACKEND_PORT}
      - API_LINK=${API_LINK}
    networks:
      - avtodiva-network

networks:
  avtodiva-network:
    external: true